var _so_x_flanger_phaser_and_tremolo___audio_processor_8cpp =
[
    [ "SoXFlangerPhaserAndTremolo_AudioProcessor", "struct_so_x_plugins_1_1_effects_1_1_so_x_flanger_phaser_and_tremolo_1_1_so_x_flanger_phaser_and_tremolo___audio_processor.html", "struct_so_x_plugins_1_1_effects_1_1_so_x_flanger_phaser_and_tremolo_1_1_so_x_flanger_phaser_and_tremolo___audio_processor" ],
    [ "createPluginFilter", "_so_x_flanger_phaser_and_tremolo___audio_processor_8cpp.html#ad8f2c863bffc2e87f6f3dc7a500b94f9", null ]
];