var searchData=
[
  ['juceplugindefines_2eh_1125',['JucePluginDefines.h',['../_so_x_chorus_and_echo_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_compander_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_filter_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_gain_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_overdrive_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_flanger_phaser_and_tremolo_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_reverb_2_juce_plugin_defines_8h.html',1,'(Global Namespace)']]],
  ['soxaudioeditor_2ecpp_1126',['SoXAudioEditor.cpp',['../_so_x_audio_editor_8cpp.html',1,'']]],
  ['soxaudioeditor_2eh_1127',['SoXAudioEditor.h',['../_so_x_audio_editor_8h.html',1,'']]],
  ['soxaudioeditorwidget_2ecpp_1128',['SoXAudioEditorWidget.cpp',['../_so_x_audio_editor_widget_8cpp.html',1,'']]],
  ['soxaudioeditorwidget_2eh_1129',['SoXAudioEditorWidget.h',['../_so_x_audio_editor_widget_8h.html',1,'']]],
  ['soxaudioeffect_2ecpp_1130',['SoXAudioEffect.cpp',['../_so_x_audio_effect_8cpp.html',1,'']]],
  ['soxaudioeffect_2eh_1131',['SoXAudioEffect.h',['../_so_x_audio_effect_8h.html',1,'']]],
  ['soxaudiohelper_2eh_1132',['SoXAudioHelper.h',['../_so_x_audio_helper_8h.html',1,'']]],
  ['soxaudioprocessor_2ecpp_1133',['SoXAudioProcessor.cpp',['../_so_x_audio_processor_8cpp.html',1,'']]],
  ['soxaudioprocessor_2eh_1134',['SoXAudioProcessor.h',['../_so_x_audio_processor_8h.html',1,'']]],
  ['soxchorusandecho_5faudioeffect_2ecpp_1135',['SoXChorusAndEcho_AudioEffect.cpp',['../_so_x_chorus_and_echo___audio_effect_8cpp.html',1,'']]],
  ['soxchorusandecho_5faudioeffect_2eh_1136',['SoXChorusAndEcho_AudioEffect.h',['../_so_x_chorus_and_echo___audio_effect_8h.html',1,'']]],
  ['soxchorusandecho_5faudioprocessor_2ecpp_1137',['SoXChorusAndEcho_AudioProcessor.cpp',['../_so_x_chorus_and_echo___audio_processor_8cpp.html',1,'']]],
  ['soxcompander_5faudioeffect_2ecpp_1138',['SoXCompander_AudioEffect.cpp',['../_so_x_compander___audio_effect_8cpp.html',1,'']]],
  ['soxcompander_5faudioeffect_2eh_1139',['SoXCompander_AudioEffect.h',['../_so_x_compander___audio_effect_8h.html',1,'']]],
  ['soxcompander_5faudioprocessor_2ecpp_1140',['SoXCompander_AudioProcessor.cpp',['../_so_x_compander___audio_processor_8cpp.html',1,'']]],
  ['soxcompandersupport_2ecpp_1141',['SoXCompanderSupport.cpp',['../_so_x_compander_support_8cpp.html',1,'']]],
  ['soxcompandersupport_2eh_1142',['SoXCompanderSupport.h',['../_so_x_compander_support_8h.html',1,'']]],
  ['soxeffectparametermap_2ecpp_1143',['SoXEffectParameterMap.cpp',['../_so_x_effect_parameter_map_8cpp.html',1,'']]],
  ['soxeffectparametermap_2eh_1144',['SoXEffectParameterMap.h',['../_so_x_effect_parameter_map_8h.html',1,'']]],
  ['soxfilter_5faudioeffect_2ecpp_1145',['SoXFilter_AudioEffect.cpp',['../_so_x_filter___audio_effect_8cpp.html',1,'']]],
  ['soxfilter_5faudioeffect_2eh_1146',['SoXFilter_AudioEffect.h',['../_so_x_filter___audio_effect_8h.html',1,'']]],
  ['soxfilter_5faudioprocessor_2ecpp_1147',['SoXFilter_AudioProcessor.cpp',['../_so_x_filter___audio_processor_8cpp.html',1,'']]],
  ['soxflangerphaserandtremolo_5faudioeffect_2ecpp_1148',['SoXFlangerPhaserAndTremolo_AudioEffect.cpp',['../_so_x_flanger_phaser_and_tremolo___audio_effect_8cpp.html',1,'']]],
  ['soxflangerphaserandtremolo_5faudioeffect_2eh_1149',['SoXFlangerPhaserAndTremolo_AudioEffect.h',['../_so_x_flanger_phaser_and_tremolo___audio_effect_8h.html',1,'']]],
  ['soxflangerphaserandtremolo_5faudioprocessor_2ecpp_1150',['SoXFlangerPhaserAndTremolo_AudioProcessor.cpp',['../_so_x_flanger_phaser_and_tremolo___audio_processor_8cpp.html',1,'']]],
  ['soxgain_5faudioeffect_2ecpp_1151',['SoXGain_AudioEffect.cpp',['../_so_x_gain___audio_effect_8cpp.html',1,'']]],
  ['soxgain_5faudioeffect_2eh_1152',['SoXGain_AudioEffect.h',['../_so_x_gain___audio_effect_8h.html',1,'']]],
  ['soxgain_5faudioprocessor_2ecpp_1153',['SoXGain_AudioProcessor.cpp',['../_so_x_gain___audio_processor_8cpp.html',1,'']]],
  ['soxoverdrive_5faudioeffect_2ecpp_1154',['SoXOverdrive_AudioEffect.cpp',['../_so_x_overdrive___audio_effect_8cpp.html',1,'']]],
  ['soxoverdrive_5faudioeffect_2eh_1155',['SoXOverdrive_AudioEffect.h',['../_so_x_overdrive___audio_effect_8h.html',1,'']]],
  ['soxoverdrive_5faudioprocessor_2ecpp_1156',['SoXOverdrive_AudioProcessor.cpp',['../_so_x_overdrive___audio_processor_8cpp.html',1,'']]],
  ['soxparametervaluechangekind_2eh_1157',['SoXParameterValueChangeKind.h',['../_so_x_parameter_value_change_kind_8h.html',1,'']]],
  ['soxplugin_2dstandalone_2ecpp_1158',['SoXPlugin-Standalone.cpp',['../_so_x_chorus_and_echo_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_compander_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_filter_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_gain_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_overdrive_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_flanger_phaser_and_tremolo_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_reverb_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)']]],
  ['soxplugin_2dutil_2ecpp_1159',['SoXPlugin-util.cpp',['../_so_x_chorus_and_echo_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_compander_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_filter_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_gain_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_overdrive_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_flanger_phaser_and_tremolo_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_reverb_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)']]],
  ['soxplugin_2dvst_5f1_2ecpp_1160',['SoxPlugin-VST_1.cpp',['../_so_x_filter_2_sox_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_gain_2_sox_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_reverb_2_sox_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_chorus_and_echo_2_so_x_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_compander_2_so_x_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_overdrive_2_so_x_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_flanger_phaser_and_tremolo_2_so_x_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)']]],
  ['soxreverb_5faudioeffect_2ecpp_1161',['SoXReverb_AudioEffect.cpp',['../_so_x_reverb___audio_effect_8cpp.html',1,'']]],
  ['soxreverb_5faudioeffect_2eh_1162',['SoXReverb_AudioEffect.h',['../_so_x_reverb___audio_effect_8h.html',1,'']]],
  ['soxreverb_5faudioprocessor_2ecpp_1163',['SoXReverb_AudioProcessor.cpp',['../_so_x_reverb___audio_processor_8cpp.html',1,'']]],
  ['soxreverbsupport_2ecpp_1164',['SoXReverbSupport.cpp',['../_so_x_reverb_support_8cpp.html',1,'']]],
  ['soxreverbsupport_2eh_1165',['SoXReverbSupport.h',['../_so_x_reverb_support_8h.html',1,'']]],
  ['stringlist_2ecpp_1166',['StringList.cpp',['../_string_list_8cpp.html',1,'']]],
  ['stringlist_2eh_1167',['StringList.h',['../_string_list_8h.html',1,'']]],
  ['stringset_2ecpp_1168',['StringSet.cpp',['../_string_set_8cpp.html',1,'']]],
  ['stringset_2eh_1169',['StringSet.h',['../_string_set_8h.html',1,'']]],
  ['stringutil_2ecpp_1170',['StringUtil.cpp',['../_string_util_8cpp.html',1,'']]],
  ['stringutil_2eh_1171',['StringUtil.h',['../_string_util_8h.html',1,'']]]
];
