var searchData=
[
  ['juceplugindefines_2eh_742',['JucePluginDefines.h',['../_so_x_compander_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_filter_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_gain_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_overdrive_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_phaser_and_tremolo_2_juce_plugin_defines_8h.html',1,'(Global Namespace)'],['../_so_x_reverb_2_juce_plugin_defines_8h.html',1,'(Global Namespace)']]],
  ['soxaudioeditor_2ecpp_743',['SoXAudioEditor.cpp',['../_so_x_audio_editor_8cpp.html',1,'']]],
  ['soxaudioeditor_2eh_744',['SoXAudioEditor.h',['../_so_x_audio_editor_8h.html',1,'']]],
  ['soxaudioeditorwidget_2ecpp_745',['SoXAudioEditorWidget.cpp',['../_so_x_audio_editor_widget_8cpp.html',1,'']]],
  ['soxaudioeditorwidget_2eh_746',['SoXAudioEditorWidget.h',['../_so_x_audio_editor_widget_8h.html',1,'']]],
  ['soxaudioeffect_2ecpp_747',['SoXAudioEffect.cpp',['../_so_x_audio_effect_8cpp.html',1,'']]],
  ['soxaudioeffect_2eh_748',['SoXAudioEffect.h',['../_so_x_audio_effect_8h.html',1,'']]],
  ['soxaudiohelper_2eh_749',['SoXAudioHelper.h',['../_so_x_audio_helper_8h.html',1,'']]],
  ['soxaudioprocessor_2ecpp_750',['SoXAudioProcessor.cpp',['../_so_x_audio_processor_8cpp.html',1,'']]],
  ['soxaudioprocessor_2eh_751',['SoXAudioProcessor.h',['../_so_x_audio_processor_8h.html',1,'']]],
  ['soxcompander_5faudioeffect_2ecpp_752',['SoXCompander_AudioEffect.cpp',['../_so_x_compander___audio_effect_8cpp.html',1,'']]],
  ['soxcompander_5faudioeffect_2eh_753',['SoXCompander_AudioEffect.h',['../_so_x_compander___audio_effect_8h.html',1,'']]],
  ['soxcompander_5faudioprocessor_2ecpp_754',['SoXCompander_AudioProcessor.cpp',['../_so_x_compander___audio_processor_8cpp.html',1,'']]],
  ['soxcompandersupport_2ecpp_755',['SoXCompanderSupport.cpp',['../_so_x_compander_support_8cpp.html',1,'']]],
  ['soxcompandersupport_2eh_756',['SoXCompanderSupport.h',['../_so_x_compander_support_8h.html',1,'']]],
  ['soxeffectparametermap_2ecpp_757',['SoXEffectParameterMap.cpp',['../_so_x_effect_parameter_map_8cpp.html',1,'']]],
  ['soxeffectparametermap_2eh_758',['SoXEffectParameterMap.h',['../_so_x_effect_parameter_map_8h.html',1,'']]],
  ['soxfilter_5faudioeffect_2ecpp_759',['SoXFilter_AudioEffect.cpp',['../_so_x_filter___audio_effect_8cpp.html',1,'']]],
  ['soxfilter_5faudioeffect_2eh_760',['SoXFilter_AudioEffect.h',['../_so_x_filter___audio_effect_8h.html',1,'']]],
  ['soxfilter_5faudioprocessor_2ecpp_761',['SoXFilter_AudioProcessor.cpp',['../_so_x_filter___audio_processor_8cpp.html',1,'']]],
  ['soxgain_5faudioeffect_2ecpp_762',['SoXGain_AudioEffect.cpp',['../_so_x_gain___audio_effect_8cpp.html',1,'']]],
  ['soxgain_5faudioeffect_2eh_763',['SoXGain_AudioEffect.h',['../_so_x_gain___audio_effect_8h.html',1,'']]],
  ['soxgain_5faudioprocessor_2ecpp_764',['SoXGain_AudioProcessor.cpp',['../_so_x_gain___audio_processor_8cpp.html',1,'']]],
  ['soxoverdrive_5faudioeffect_2ecpp_765',['SoXOverdrive_AudioEffect.cpp',['../_so_x_overdrive___audio_effect_8cpp.html',1,'']]],
  ['soxoverdrive_5faudioeffect_2eh_766',['SoXOverdrive_AudioEffect.h',['../_so_x_overdrive___audio_effect_8h.html',1,'']]],
  ['soxoverdrive_5faudioprocessor_2ecpp_767',['SoXOverdrive_AudioProcessor.cpp',['../_so_x_overdrive___audio_processor_8cpp.html',1,'']]],
  ['soxparametervaluechangekind_2eh_768',['SoXParameterValueChangeKind.h',['../_so_x_parameter_value_change_kind_8h.html',1,'']]],
  ['soxphaserandtremolo_5faudioeffect_2ecpp_769',['SoXPhaserAndTremolo_AudioEffect.cpp',['../_so_x_phaser_and_tremolo___audio_effect_8cpp.html',1,'']]],
  ['soxphaserandtremolo_5faudioeffect_2eh_770',['SoXPhaserAndTremolo_AudioEffect.h',['../_so_x_phaser_and_tremolo___audio_effect_8h.html',1,'']]],
  ['soxphaserandtremolo_5faudioprocessor_2ecpp_771',['SoXPhaserAndTremolo_AudioProcessor.cpp',['../_so_x_phaser_and_tremolo___audio_processor_8cpp.html',1,'']]],
  ['soxplugin_2dstandalone_2ecpp_772',['SoXPlugin-Standalone.cpp',['../_so_x_compander_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_filter_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_gain_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_overdrive_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_phaser_and_tremolo_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)'],['../_so_x_reverb_2_so_x_plugin-_standalone_8cpp.html',1,'(Global Namespace)']]],
  ['soxplugin_2dutil_2ecpp_773',['SoXPlugin-util.cpp',['../_so_x_compander_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_filter_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_gain_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_overdrive_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_phaser_and_tremolo_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)'],['../_so_x_reverb_2_so_x_plugin-util_8cpp.html',1,'(Global Namespace)']]],
  ['soxplugin_2dvst_5f1_2ecpp_774',['SoxPlugin-VST_1.cpp',['../_so_x_filter_2_sox_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_gain_2_sox_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_phaser_and_tremolo_2_sox_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_reverb_2_sox_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_compander_2_so_x_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)'],['../_so_x_overdrive_2_so_x_plugin-_v_s_t__1_8cpp.html',1,'(Global Namespace)']]],
  ['soxplugin_2dvst_5f2_2ecpp_775',['SoXPlugin-VST_2.cpp',['../_so_x_compander_2_so_x_plugin-_v_s_t__2_8cpp.html',1,'(Global Namespace)'],['../_so_x_filter_2_so_x_plugin-_v_s_t__2_8cpp.html',1,'(Global Namespace)'],['../_so_x_gain_2_so_x_plugin-_v_s_t__2_8cpp.html',1,'(Global Namespace)'],['../_so_x_overdrive_2_so_x_plugin-_v_s_t__2_8cpp.html',1,'(Global Namespace)'],['../_so_x_phaser_and_tremolo_2_so_x_plugin-_v_s_t__2_8cpp.html',1,'(Global Namespace)'],['../_so_x_reverb_2_so_x_plugin-_v_s_t__2_8cpp.html',1,'(Global Namespace)']]],
  ['soxreverb_5faudioeffect_2ecpp_776',['SoXReverb_AudioEffect.cpp',['../_so_x_reverb___audio_effect_8cpp.html',1,'']]],
  ['soxreverb_5faudioeffect_2eh_777',['SoXReverb_AudioEffect.h',['../_so_x_reverb___audio_effect_8h.html',1,'']]],
  ['soxreverb_5faudioprocessor_2ecpp_778',['SoXReverb_AudioProcessor.cpp',['../_so_x_reverb___audio_processor_8cpp.html',1,'']]],
  ['soxreverbsupport_2ecpp_779',['SoXReverbSupport.cpp',['../_so_x_reverb_support_8cpp.html',1,'']]],
  ['soxreverbsupport_2eh_780',['SoXReverbSupport.h',['../_so_x_reverb_support_8h.html',1,'']]],
  ['stringlist_2ecpp_781',['StringList.cpp',['../_string_list_8cpp.html',1,'']]],
  ['stringlist_2eh_782',['StringList.h',['../_string_list_8h.html',1,'']]],
  ['stringset_2eh_783',['StringSet.h',['../_string_set_8h.html',1,'']]],
  ['stringutil_2ecpp_784',['StringUtil.cpp',['../_string_util_8cpp.html',1,'']]],
  ['stringutil_2eh_785',['StringUtil.h',['../_string_util_8h.html',1,'']]]
];
